import BaseWriter from '../Writer';
import { GenericNodeVisitor, SkipChildren } from '../nodes';
import { defaultSections } from './rstConfig';
import {Settings} from "../../gen/Settings";
import {Document, ElementInterface, NodeInterface} from "../types";

/* eslint-disable-next-line no-console */
console.log = process.stderr.write;

/* eslint-disable-next-line @typescript-eslint/no-unused-vars,no-unused-vars */
const __version__ = '';
/* eslint-disable-next-line @typescript-eslint/no-unused-vars,no-unused-vars */
const __docformat__ = 'reStructuredText';

/**
 * Translator class for Pojo writer
 */
class RSTTranslator extends GenericNodeVisitor {
    private lines: string[];
    private indent: number;
    private curLine: string;
    private sectionNum: number;
    private ancestors: any[];
    private level: number;
    private root: any | undefined;
    private output: any;
    private settings: Settings;
    private warn: OmitThisParameter<(...args: any[]) => NodeInterface>;
    private inSimple: number;
    private fixedText: number;
    private error: OmitThisParameter<(...args: any[]) => NodeInterface>;
    /**
     * Create a RSTTranslator
     * @param {nodes.document} document - the document to translate
     */
    public constructor(document: Document) {
        super(document);
        if (!defaultSections) {
            throw new Error();
        }
        this.ancestors = [];
        this.document = document;
        this.lines = [];
        this.indent = 0;
        this.sectionNum = 0;
        if (!this.document.reporter) {
            throw new Error('document has no reporter');
        }
        this.warn = this.document.reporter.warning.bind(this.document.reporter);
        this.error = this.document.reporter.error.bind(this.document.reporter);

        this.settings = document.settings;
        this.level = 0;
        this.inSimple = 0;
        this.fixedText = 0;
        this.output = {};
        this.curLine = '';
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase */
    public default_visit(node: NodeInterface) {
        if (node.tagname && (<ElementInterface>node).attlist) {
            const me = [node.tagname, (<ElementInterface>node).attlist(), []];
            //            console.log(me);
            this.ancestors.push(me);
            this.level += 1;
        } else {
            //            console.log(node.astext());
        }

        //      console.log(this.level);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars */
    public default_departure(node: NodeInterface) {
        const me = this.ancestors.pop();
        if (this.level === 1) {
            this.root = me;
            //          console.log(JSON.stringify(me));
        } else {
            const parent = this.ancestors[this.ancestors.length - 1];
            parent[2].push(me);
        }
        this.level -= 1;
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase */
    public visit_Text(node: NodeInterface) {
        this.default_visit(node);
        this.ancestors[this.ancestors.length - 1][2].push(node.astext());
        this.curLine += node.astext();
        //      const text = escapeXml(node.astext())
        //      this.output.push(text);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars */
    public depart_Text(node: NodeInterface) {
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_header(node: NodeInterface) {
        /* I believe this is typically generated by a transform. */
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_header(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_footer(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_footer(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_decoration(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_decoration(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_document(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_document(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_docinfo(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_docinfo(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_authors(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_authors(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_section(node: NodeInterface) {
        this.sectionNum += 1;
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_section(node: NodeInterface) {
        this.sectionNum -= 1;
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_topic(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_topic(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_sidebar(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_sidebar(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_transition(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_transition(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_compound(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_compound(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_container(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_container(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_bullet_list(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_bullet_list(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_enumerated_list(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_enumerated_list(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_list_item(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_list_item(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_definition_list(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_definition_list(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_definition_list_item(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_definition_list_item(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_definition(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_definition(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_field_list(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_field_list(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_field(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_field(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_field_body(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_field_body(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_option(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_option(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_option_group(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_option_group(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_option_list(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_option_list(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_option_list_item(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_option_list_item(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_description(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_description(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_line_block(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_line_block(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_block_quote(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_block_quote(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_attention(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_attention(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_caution(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_caution(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_danger(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_danger(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_error(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_error(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_important(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_important(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_note(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_note(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_tip(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_tip(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_hint(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_hint(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_warning(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_warning(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_admonition(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_admonition(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_footnote(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_footnote(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_citation(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_citation(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_figure(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_figure(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_legend(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_legend(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_table(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_table(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_tgroup(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_tgroup(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_colspec(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_colspec(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_thead(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_thead(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_tbody(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_tbody(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_row(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_row(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_entry(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_entry(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_system_message(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_system_message(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_pending(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_pending(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_image(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_image(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_title(node: NodeInterface) {
        this.default_visit(node);
        this.newLine();
        const title = node.astext();
        //        console.log(this.sectionNum);
        const sectSpec = defaultSections[this.sectionNum - 1];
        let index = 0;
        if (sectSpec.length === 2) {
            this.addLine(sectSpec[index].repeat(title.length));
            index += 1;
        }
        this.addLine(title);
        this.addLine(sectSpec[index].repeat(title.length));
        this.newLine(true);
        throw new SkipChildren();
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_title(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_subtitle(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_subtitle(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_rubric(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_rubric(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_author(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_author(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_organization(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_organization(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_contact(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_contact(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_version(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_version(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_revision(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_revision(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_status(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_status(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_date(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_date(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_copyright(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_copyright(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_paragraph(node: NodeInterface) {
        this.default_visit(node);
        this.newLine(true);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_paragraph(node: NodeInterface) {
        this.default_departure(node);
        this.newLine(true);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_term(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_term(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_classifier(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_classifier(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_field_name(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_field_name(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_option_argument(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_option_argument(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_option_string(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_option_string(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_line(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_line(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_attribution(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_attribution(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_substitution_definition(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_substitution_definition(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_target(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_target(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_label(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_label(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_caption(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_caption(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_emphasis(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_emphasis(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_strong(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_strong(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_literal(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_literal(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_reference(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_reference(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_footnote_reference(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_footnote_reference(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_citation_reference(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_citation_reference(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_substitution_reference(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_substitution_reference(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_title_reference(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_title_reference(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_abbreviation(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_abbreviation(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_acronym(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_acronym(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_superscript(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_superscript(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_subscript(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_subscript(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_math(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_math(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_inline(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_inline(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_problematic(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_problematic(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_generated(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_generated(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_address(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_address(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_literal_block(node: NodeInterface) {
        this.default_visit(node);
        const lastLine = this.getLastLine();
        if (lastLine.endsWith(':')) {
            this.lines[this.lines.length - 1] += ':';
        }
        this.indent += 4;
        if (!this.curLine.trim()) {
            this.curLine = ' '.repeat(this.indent);
        }
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_literal_block(node: NodeInterface) {
        this.default_departure(node);
        this.newLine(true);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_doctest_block(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_doctest_block(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_math_block(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_math_block(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_comment(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_comment(node: NodeInterface) {
        this.default_departure(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public visit_raw(node: NodeInterface) {
        this.default_visit(node);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars,class-methods-use-this */
    public depart_raw(node: NodeInterface) {
        this.default_departure(node);
    }

    public newLine(allowBlankLine: boolean = false) {
        if (this.curLine || allowBlankLine) {
            this.lines.push(this.curLine);
        }
        this.curLine = ' '.repeat(this.indent);
    }

    public addLine(line: string) {
        if (this.curLine) {
            throw new Error();
        }
        this.lines.push(' '.repeat(this.indent) + line);
    }

    public getLastLine() {
        return this.lines[this.lines.length - 1];
    }
}

/**
 * Writer class for POJOWriter
 */
class RSTWriter extends BaseWriter {
    private visitor: any;
    private translatorClass: any;
    /**
     * Create POJOWriter
     * @param {Object} args - Arguments, none right now
     */
    public constructor() {
        super();
        this.translatorClass = RSTTranslator;
    }

    /**
     * Translate the document to plain old javascript object
     */
    public translate() {
        const TranslatorClass = this.translatorClass;
        const visitor = new TranslatorClass(this.document);
        this.visitor = visitor;
        this.document!.walkabout(visitor);
        this.output = visitor.lines;
    }
}

/*POJOWriter.settingsSpec = [
    '"Docutils-js POJO" Writer Options',
    null,
    []];

 */
export default RSTWriter;
