export default {
tocEntryBacklinks: 'entry',
footnoteBacklinks: 1,
sectionNumbering: 1,
report: 2,
halt: 4,
exitStatus: 5,
traceback: null,
inputEncodingErrorHandler: 'strict',
outputEncoding: 'utf-8',
outputEncodingErrorHandler: 'strict',
errorEncoding: 'UTF-8',
errorEncodingErrorHandler: 'backslashreplace',
language: 'en',
recordDependencies: null,
idPrefix: '',
autoIdPrefix: 'id',
pepBaseUrl: 'http://www.python.org/dev/peps/',
pepFileUrlTemplate: 'pep-%04d',
rfcBaseUrl: 'http://tools.ietf.org/html/',
tabWidth: 8,
noFileInsertion: 1,
noRaw: 1,
syntaxHighlight: 'long',
smartQuotes: false,
characterLevelInlineMarkup: false,
noXmlDeclaration: 1,
noDoctype: 1,
noDocTitle: 1,
noDocInfo: 1,
sectionSubtitles: 0,
}

