export default interface Settings {
/** frontend: Specify the document title as metadata. */
title: any;
/** frontend: Include a "Generated by Docutils" credit and link. */
generator: boolean;
/** frontend: Do not include a generator credit. */
noGenerator: any;
/** frontend: Include the date at the end of the document (UTC). */
date: any;
/** frontend: Include the time & date (UTC). */
time: any;
/** frontend: Do not include a datestamp of any kind. */
noDatestamp: any;
/** frontend: Include a "View document source" link. */
sourceLink: boolean;
/** frontend: Use <URL> for a source link; implies --source-link. */
sourceUrl: any;
/** frontend: Do not include a "View document source" link. */
noSourceLink: any;
/** frontend: Link from section headers to TOC entries.  (default) */
tocEntryBacklinks: any;
/** frontend: Link from section headers to the top of the TOC. */
tocTopBacklinks: any;
/** frontend: Disable backlinks to the table of contents. */
noTocBacklinks: any;
/** frontend: Link from footnotes/citations to references. (default) */
footnoteBacklinks: boolean;
/** frontend: Disable backlinks from footnotes and citations. */
noFootnoteBacklinks: any;
/** frontend: Enable section numbering by Docutils.  (default) */
sectionNumbering: boolean;
/** frontend: Disable section numbering by Docutils. */
noSectionNumbering: any;
/** frontend: Remove comment elements from the document tree. */
stripComments: boolean;
/** frontend: Leave comment elements in the document tree. (default) */
leaveComments: any;
/** frontend: Remove all elements with classes="<class>" from the document tree. Warning: potentially dangerous; use with caution. (Multiple-use option.) */
stripElementsWithClass: any;
/** frontend: Remove all classes="<class>" attributes from elements in the document tree. Warning: potentially dangerous; use with caution. (Multiple-use option.) */
stripClass: any;
/** frontend: Report system messages at or higher than <level>: "info" or "1", "warning"/"2" (default), "error"/"3", "severe"/"4", "none"/"5" */
report: any;
/** frontend: Report all system messages.  (Same as "--report=1".) */
verbose: any;
/** frontend: Report no system messages.  (Same as "--report=5".) */
quiet: any;
/** frontend: Halt execution at system messages at or above <level>.  Levels as in --report.  Default: 4 (severe). */
halt: any;
/** frontend: Halt at the slightest problem.  Same as "--halt=info". */
strict: any;
/** frontend: Enable a non-zero exit status for non-halting system messages at or above <level>.  Default: 5 (disabled). */
exitStatus: any;
/** frontend: Enable debug-level system messages and diagnostics. */
debug: boolean;
/** frontend: Disable debug output.  (default) */
noDebug: any;
/** frontend: Send the output of system messages to <file>. */
warnings: any;
/** frontend: Enable Python tracebacks when Docutils is halted. */
traceback: boolean;
/** frontend: Disable Python tracebacks.  (default) */
noTraceback: any;
/** frontend: Specify the encoding and optionally the error handler of input text.  Default: <locale-dependent>:strict. */
inputEncoding: any;
/** frontend: Specify the error handler for undecodable characters.  Choices: "strict" (default), "ignore", and "replace". */
inputEncodingErrorHandler: any;
/** frontend: Specify the text encoding and optionally the error handler for output.  Default: UTF-8:strict. */
outputEncoding: any;
/** frontend: Specify error handler for unencodable output characters; "strict" (default), "ignore", "replace", "xmlcharrefreplace", "backslashreplace". */
outputEncodingErrorHandler: any;
/** frontend: Specify text encoding and error handler for error output.  Default text encoding: system encoding. Default error handler: backslashreplace. */
errorEncoding: any;
/** frontend: Specify the error handler for unencodable characters in error output.  Default: backslashreplace. */
errorEncodingErrorHandler: any;
/** frontend: Specify the language (as BCP 47 language tag).  Default: en. */
language: any;
/** frontend: Write output file dependencies to <file>. */
recordDependencies: any;
/** frontend: Read configuration settings from <file>, if it exists. */
config: any;
/** frontend: Show this program's version number and exit. */
version: any;
/** frontend: Show this help message and exit. */
help: any;
/** frontend: SUPPRESSHELP */
idPrefix: any;
/** frontend: SUPPRESSHELP */
autoIdPrefix: any;
/** frontend: SUPPRESSHELP */
dumpSettings: any;
/** frontend: SUPPRESSHELP */
dumpInternals: any;
/** frontend: SUPPRESSHELP */
dumpTransforms: any;
/** frontend: SUPPRESSHELP */
dumpPseudoXml: any;
/** frontend: SUPPRESSHELP */
exposeInternalAttribute: any;
/** frontend: SUPPRESSHELP */
strictVisitor: any;
/** standaloneReader: Disable the promotion of a lone top-level section title to document title (and subsequent section title to document subtitle promotion; enabled by default). */
noDocTitle: boolean;
/** standaloneReader: Disable the bibliographic field list transform (enabled by default). */
noDocInfo: boolean;
/** standaloneReader: Activate the promotion of lone subsection titles to section subtitles (disabled by default). */
sectionSubtitles: boolean;
/** standaloneReader: Deactivate the promotion of lone subsection titles. */
noSectionSubtitles: any;
/** rstParser: Recognize and link to standalone PEP references (like "PEP 258"). */
pepReferences: boolean;
/** rstParser: Base URL for PEP references (default "http://www.python.org/dev/peps/"). */
pepBaseUrl: any;
/** rstParser: Template for PEP file part of URL. (default "pep-%04d") */
pepFileUrlTemplate: any;
/** rstParser: Recognize and link to standalone RFC references (like "RFC 822"). */
rfcReferences: boolean;
/** rstParser: Base URL for RFC references (default "http://tools.ietf.org/html/"). */
rfcBaseUrl: any;
/** rstParser: Set number of spaces for tab expansion (default 8). */
tabWidth: any;
/** rstParser: Remove spaces before footnote references. */
trimFootnoteReferenceSpace: boolean;
/** rstParser: Leave spaces before footnote references. */
leaveFootnoteReferenceSpace: any;
/** rstParser: Disable directives that insert the contents of external file ("include" & "raw"); replaced with a "warning" system message. */
noFileInsertion: boolean;
/** rstParser: Enable directives that insert the contents of external file ("include" & "raw").  Enabled by default. */
fileInsertionEnabled: any;
/** rstParser: Disable the "raw" directives; replaced with a "warning" system message. */
noRaw: boolean;
/** rstParser: Enable the "raw" directive.  Enabled by default. */
rawEnabled: any;
/** rstParser: Token name set for parsing code with Pygments: one of "long", "short", or "none (no parsing)". Default is "long". */
syntaxHighlight: any;
/** rstParser: Change straight quotation marks to typographic form: one of "yes", "no", "alt[ernative]" (default "no"). */
smartQuotes: any;
/** rstParser: Characters to use as "smart quotes" for <language>.  */
smartquotesLocales: any;
/** rstParser: Inline markup recognized at word boundaries only (adjacent to punctuation or whitespace). Force character-level inline markup recognition with "\ " (backslash + space). Default. */
wordLevelInlineMarkup: any;
/** rstParser: Inline markup recognized anywhere, regardless of surrounding characters. Backslash-escapes must be used to avoid unwanted markup recognition. Useful for East Asian languages. Experimental. */
characterLevelInlineMarkup: any;
/** xmlWriter: Generate XML with newlines before and after tags. */
newlines: boolean;
/** xmlWriter: Generate XML with indents and newlines. */
indents: boolean;
/** xmlWriter: Omit the XML declaration.  Use with caution. */
noXmlDeclaration: boolean;
/** xmlWriter: Omit the DOCTYPE declaration. */
noDoctype: boolean;
}
