import { getDefaultSettings } from "../src/settingsHelper";

test("1", () => {
    expect(getDefaultSettings()).toMatchInlineSnapshot(`
    Object {
      "docutilsCoreOptionParser": Object {
        "autoIdPrefix": "id",
        "errorEncoding": "UTF-8",
        "errorEncodingErrorHandler": "backslashreplace",
        "exitStatusLevel": 5,
        "footnoteBacklinks": 1,
        "haltLevel": 4,
        "idPrefix": "",
        "inputEncodingErrorHandler": "strict",
        "languageCode": "en",
        "outputEncoding": "utf-8",
        "outputEncodingErrorHandler": "strict",
        "recordDependencies": undefined,
        "reportLevel": 2,
        "sectnumXform": 1,
        "tocBacklinks": "entry",
        "traceback": undefined,
      },
      "docutilsFrontendOptionParser": Object {
        "autoIdPrefix": "id",
        "errorEncoding": "UTF-8",
        "errorEncodingErrorHandler": "backslashreplace",
        "exitStatusLevel": 5,
        "footnoteBacklinks": 1,
        "haltLevel": 4,
        "idPrefix": "",
        "inputEncodingErrorHandler": "strict",
        "languageCode": "en",
        "outputEncoding": "utf-8",
        "outputEncodingErrorHandler": "strict",
        "recordDependencies": undefined,
        "reportLevel": 2,
        "sectnumXform": 1,
        "tocBacklinks": "entry",
        "traceback": undefined,
      },
      "docutilsParsersRstParser": Object {
        "characterLevelInlineMarkup": false,
        "fileInsertionEnabled": 1,
        "pepBaseUrl": "http://www.python.org/dev/peps/",
        "pepFileUrlTemplate": "pep-%04d",
        "rawEnabled": 1,
        "rfcBaseUrl": "http://tools.ietf.org/html/",
        "smartQuotes": false,
        "syntaxHighlight": "long",
        "tabWidth": 8,
      },
      "docutilsReadersStandaloneReader": Object {
        "docinfoXform": true,
        "doctitleXform": true,
        "sectsubtitleXform": false,
      },
      "docutilsWritersDocutilsXmlWriter": Object {
        "doctypeDeclaration": true,
        "xmlDeclaration": true,
      },
      "docutilsWritersHtml4Css1Writer": Object {
        "attribution": "dash",
        "compactFieldLists": 1,
        "compactLists": 1,
        "embedStylesheet": 1,
        "fieldNameLimit": 14,
        "footnoteReferences": "brackets",
        "initialHeaderLevel": 1,
        "mathOutput": "HTML math.css",
        "optionLimit": 14,
        "stylesheetDirs": Array [
          ".",
          "/usr/share/docutils/writers/html4css1",
          "/usr/share/docutils/writers/html5_polyglot",
        ],
        "stylesheetPath": Array [
          "html4css1.css",
        ],
        "tableStyle": "",
        "template": "/usr/share/docutils/writers/html4css1/template.txt",
        "xmlDeclaration": true,
      },
      "docutilsWritersPepHtmlWriter": Object {
        "attribution": "dash",
        "compactFieldLists": 1,
        "compactLists": 1,
        "embedStylesheet": 1,
        "fieldNameLimit": 14,
        "footnoteReferences": "brackets",
        "initialHeaderLevel": "1",
        "mathOutput": "HTML math.css",
        "optionLimit": 14,
        "stylesheetDirs": Array [
          ".",
          "/usr/share/docutils/writers/html4css1",
          "/usr/share/docutils/writers/html5_polyglot",
        ],
        "stylesheetPath": Array [
          "html4css1.css",
        ],
        "tableStyle": "",
        "template": "/usr/share/docutils/writers/html4css1/template.txt",
        "xmlDeclaration": true,
      },
    }
  `);
});
