import { getDefaultSettings } from "../src/settingsHelper";

test("1", () => {
  expect(getDefaultSettings()).toMatchInlineSnapshot(`
    Object {
      "docutilsCoreOptionParser": Object {
        "autoIdPrefix": "id",
        "errorEncoding": "UTF-8",
        "errorEncodingErrorHandler": "backslashreplace",
        "exitStatusLevel": 5,
        "footnoteBacklinks": 1,
        "haltLevel": 4,
        "idPrefix": "",
        "inputEncodingErrorHandler": "strict",
        "languageCode": "en",
        "outputEncoding": "utf-8",
        "outputEncodingErrorHandler": "strict",
        "recordDependencies": null,
        "reportLevel": 2,
        "sectnumXform": 1,
        "tocBacklinks": "entry",
        "traceback": null,
      },
      "docutilsFrontendOptionParser": Object {
        "autoIdPrefix": "id",
        "errorEncoding": "UTF-8",
        "errorEncodingErrorHandler": "backslashreplace",
        "exitStatusLevel": 5,
        "footnoteBacklinks": 1,
        "haltLevel": 4,
        "idPrefix": "",
        "inputEncodingErrorHandler": "strict",
        "languageCode": "en",
        "outputEncoding": "utf-8",
        "outputEncodingErrorHandler": "strict",
        "recordDependencies": null,
        "reportLevel": 2,
        "sectnumXform": 1,
        "tocBacklinks": "entry",
        "traceback": null,
      },
      "docutilsParsersRstParser": Object {
        "characterLevelInlineMarkup": false,
        "fileInsertionEnabled": 1,
        "pepBaseUrl": "http://www.python.org/dev/peps/",
        "pepFileUrlTemplate": "pep-%04d",
        "rawEnabled": 1,
        "rfcBaseUrl": "http://tools.ietf.org/html/",
        "smartQuotes": false,
        "syntaxHighlight": "long",
        "tabWidth": 8,
      },
      "docutilsReadersPepReader": Object {},
      "docutilsReadersStandaloneReader": Object {
        "docinfoXform": 1,
        "doctitleXform": 1,
        "sectsubtitleXform": 0,
      },
      "docutilsWritersDocutilsXmlWriter": Object {
        "doctypeDeclaration": 1,
        "xmlDeclaration": 1,
      },
      "docutilsWritersHtml4Css1Writer": Object {
        "attribution": "dash",
        "compactFieldLists": 1,
        "compactLists": 1,
        "embedStylesheet": 1,
        "fieldNameLimit": 14,
        "footnoteReferences": "brackets",
        "initialHeaderLevel": "1",
        "mathOutput": "HTML math.css",
        "optionLimit": 14,
        "stylesheetDirs": Array [
          ".",
          "/usr/share/docutils/writers/html4css1",
          "/usr/share/docutils/writers/html5_polyglot",
        ],
        "stylesheetPath": Array [
          "html4css1.css",
        ],
        "tableStyle": "",
        "template": "/usr/share/docutils/writers/html4css1/template.txt",
        "xmlDeclaration": true,
      },
      "docutilsWritersHtml5PolyglotWriter": Object {
        "attribution": "dash",
        "compactFieldLists": true,
        "compactLists": true,
        "embedStylesheet": 1,
        "footnoteReferences": "brackets",
        "initialHeaderLevel": "1",
        "mathOutput": "HTML math.css",
        "stylesheetDirs": Array [
          ".",
          "/usr/share/docutils/writers/html5_polyglot",
        ],
        "stylesheetPath": Array [
          "minimal.css",
          "plain.css",
        ],
        "tableStyle": "",
        "template": "/usr/share/docutils/writers/html5_polyglot/template.txt",
        "xmlDeclaration": false,
      },
      "docutilsWritersLatex2EWriter": Object {
        "attribution": "dash",
        "compoundEnumerators": null,
        "documentclass": "article",
        "documentoptions": "a4paper",
        "docutilsFootnotes": true,
        "embedStylesheet": 0,
        "fontEncoding": "T1",
        "footnoteReferences": "superscript",
        "graphicxOption": "",
        "hyperlinkColor": "blue",
        "hyperrefOptions": "",
        "latexPreamble": "% PDF Standard Fonts
    \\\\usepackage{mathptmx} % Times
    \\\\usepackage[scaled=.90]{helvet}
    \\\\usepackage{courier}",
        "literalBlockEnv": "",
        "referenceLabel": null,
        "sectionEnumeratorSeparator": "-",
        "sectionPrefixForEnumerators": null,
        "stylesheet": "",
        "stylesheetDirs": Array [
          ".",
        ],
        "tableStyle": Array [
          "standard",
        ],
        "template": "default.tex",
        "useBibtex": null,
        "useLatexAbstract": 0,
        "useLatexCitations": false,
        "useLatexDocinfo": 0,
        "useLatexToc": 1,
        "usePartSection": 0,
        "useVerbatimWhenPossible": 0,
      },
      "docutilsWritersOdfOdtReader": Object {
        "docinfoXform": 1,
        "doctitleXform": 1,
        "sectsubtitleXform": 0,
      },
      "docutilsWritersOdfOdtWriter": Object {
        "addSyntaxHighlighting": false,
        "cloakEmailAddresses": false,
        "createLinks": false,
        "createSections": true,
        "customFooter": "",
        "customHeader": "",
        "endnotesEndDoc": false,
        "generateOowriterToc": true,
        "stylesheet": "/usr/share/docutils/writers/odf_odt/styles.odt",
        "tableBorderThickness": null,
      },
      "docutilsWritersPepHtmlWriter": Object {
        "attribution": "dash",
        "compactFieldLists": 1,
        "compactLists": 1,
        "embedStylesheet": 1,
        "fieldNameLimit": 14,
        "footnoteReferences": "brackets",
        "initialHeaderLevel": "1",
        "mathOutput": "HTML math.css",
        "optionLimit": 14,
        "stylesheetDirs": Array [
          ".",
          "/usr/share/docutils/writers/html4css1",
          "/usr/share/docutils/writers/html5_polyglot",
        ],
        "stylesheetPath": Array [
          "html4css1.css",
        ],
        "tableStyle": "",
        "template": "/usr/share/docutils/writers/html4css1/template.txt",
        "xmlDeclaration": 1,
      },
      "docutilsWritersS5HtmlWriter": Object {
        "attribution": "dash",
        "compactFieldLists": 1,
        "compactLists": 1,
        "embedStylesheet": 1,
        "fieldNameLimit": 14,
        "footnoteReferences": "brackets",
        "initialHeaderLevel": "1",
        "mathOutput": "HTML math.css",
        "optionLimit": 14,
        "stylesheetDirs": Array [
          ".",
          "/usr/share/docutils/writers/html4css1",
          "/usr/share/docutils/writers/html5_polyglot",
        ],
        "stylesheetPath": Array [
          "html4css1.css",
        ],
        "tableStyle": "",
        "template": "/usr/share/docutils/writers/html4css1/template.txt",
        "xmlDeclaration": 1,
      },
      "docutilsWritersXetexWriter": Object {
        "attribution": "dash",
        "compoundEnumerators": null,
        "documentclass": "article",
        "documentoptions": "a4paper",
        "docutilsFootnotes": true,
        "embedStylesheet": 0,
        "footnoteReferences": "superscript",
        "graphicxOption": "",
        "hyperlinkColor": "blue",
        "hyperrefOptions": "",
        "latexPreamble": "% Linux Libertine (free, wide coverage, not only for Linux)
    \\\\setmainfont{Linux Libertine O}
    \\\\setsansfont{Linux Biolinum O}
    \\\\setmonofont[HyphenChar=None,Scale=MatchLowercase]{DejaVu Sans Mono}",
        "literalBlockEnv": "",
        "referenceLabel": null,
        "sectionEnumeratorSeparator": "-",
        "sectionPrefixForEnumerators": null,
        "stylesheet": "",
        "stylesheetDirs": Array [
          ".",
        ],
        "tableStyle": Array [
          "standard",
        ],
        "template": "xelatex.tex",
        "useBibtex": null,
        "useLatexAbstract": 0,
        "useLatexCitations": 0,
        "useLatexDocinfo": 0,
        "useLatexToc": 1,
        "usePartSection": 0,
        "useVerbatimWhenPossible": 0,
      },
    }
  `);
});
